[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

[dev]
  command = "npm run dev:netlify"
  port = 3000
  targetPort = 3000
  framework = "react"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
